name: Run ShareIt Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build application
        run: mvn clean package -DskipTests

      - name: Install Newman
        run: npm install -g newman

      - name: Run Application and Tests
        run: |
          # Запускаем приложение в фоне
          java -jar target/*.jar &
          APP_PID=$!
          
          # Ждем пока приложение запустится
          echo "Waiting for application to start..."
          sleep 60
          
          # Запускаем тесты
          newman run ./tests/postman/sprint.json \
            --delay-request 50 \
            -r cli,htmlextra \
            --reporter-htmlextra-export reports/shareIt.html \
            --reporter-htmlextra-title "Отчет по тестам"
          
          # Останавливаем приложение
          kill $APP_PID